# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: timenow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timenow
  template:
    metadata:
      labels:
        app: timenow
    spec:
      containers:
      - name: timenow
        image: 416430292789.dkr.ecr.ap-south-1.amazonaws.com/timenow:latest
        ports:
        - containerPort: 5000
